### ISSUE TITLE
关于是否要加multiDexEnabled true的问题

### ISSUE THREAD

**Issue by codeccc** [typ0520/fastdex#15]
按流程接入项目Run项目后总是报Cannot resolve which method to invoke for [null] due to overlapping prototypes 的错误,包括新建的项目也一样,仔细阅读了一下文档说是fastdex打出来的包项目所有的代码都在第二个dex后面,所以必须配置multiDexEnabled true才能正常启动吗

**Comment by typ0520** [comment]
@FancyOnePoint 不强制加multiDexEnabled true
FileUtils里有两个方法，传null的时候不知道选择哪个方法了，估计是这个问题，我改个名字试试
 
    public static boolean isLegalFile(String path) {
        if (path == null) {
            return false;
        }
        return isLegalFile(new File(path));
    }

    public static boolean isLegalFile(File file) {
        if (file == null) {
            return false;
        }
        return file.exists() && file.isFile() && file.length() > 0;
    }

**Comment by typ0520** [comment]
@FancyOnePoint 换这个版本0.0.3-beta5，在试试

**Comment by codeccc** [comment]
gradle 版本2.14.1 ,windows,关闭mutidex,instantrun
使用 版本0.0.3-beta5，提示如下错误
```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> ==fastdex normal transform merge jar fail: 
outputJar: null
```
这是执行`gradlew.bat assembleDebug --stacktrace` 打印出来的日志

```
:app:generateDebugSources                  
:app:dataBindingExportBuildInfoDebug                 
:app:fastdexCustomCompileDebugJavaWithJavac
==fastdex clean dir: C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\fastdex\Debug
==fastdex useCustomCompile=false,disable customJavacTask
:app:incrementalDebugJavaCompilationSafeguard                 
:app:compileDebugJavaWithJavac                 
build config error: skipping missing, empty or corrupt aspectpath entry: C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\ core.jar
incorrect classpath: C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\ core.jar
:app:compileDebugNdk UP-TO-DATE                
:app:compileDebugSources
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE      
:app:transformClassesWithDexForDebug                 
==fastdex normal transform start
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\alipaySingle-20161222.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\AMap_Location_V3.2.0_20161206.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\core.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\jsoup-1.10.2.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\libammsdk.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\umeng-analytics-v6.0.9.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\libs\utdid4all-1.0.4.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-v4\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-core-ui\25.0.1\jars\libs\internal_impl-25.0.1.j
ar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\recyclerview-v7\24.0.0\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.edmodo\cropper\1.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.kymjs.core\themvp\1.0.7\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\me.relex\circleindicator\1.2.2\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\me.biubiubiu.justifytext\library\1.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-core-utils\25.0.1\jars\libs\internal_impl-25.0.
1.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjrt\1.8.5\39a8ff2d1f79267907f5573c090b342b040b9682\aspectjrt-1.8.5.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-fragment\25.0.1\jars\libs\internal_impl-25.0.1.
jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.squareup.haha\haha\2.0.3\640a438d2d415c056ca6a673ac26b183b044e160\haha-2.0.3.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.jph.takephoto\takephoto_library\4.0.3\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-media-compat\25.0.1\jars\libs\internal_impl-25.
0.1.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-core-ui\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.darsh.multipleimageselect\multipleimageselect\1.0.4\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.databinding\library\1.2.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.github.markzhai\blockcanary-android\1.5.0\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.android.databinding\baseLibrary\2.2.3\b4b51d1925cdfda98fd861230c1ecb5855500129\baseLibrary-2.2.3.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.github.sendtion\XRichText\1.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-compat\25.0.1\jars\libs\internal_impl-25.0.1.ja
r
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\design\24.0.0\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.antfortune.freeline\runtime\0.8.7\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\animated-vector-drawable\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.baoyz.pullrefreshlayout\library\1.2.0\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.alibaba\fastjson\1.2.22\3f9fc4168f6f23d49de6a2782176beb11ab3f31a\fastjson-1.2.22.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.zhy\magic-viewpager\1.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.databinding\adapters\1.2.1\jars\classes.jar
==fastdex add jar C:\Android_SDK\build-tools\24.0.0\renderscript\lib\renderscript-v8.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\org.greenrobot\eventbus\3.0.0\ddd99896e9569eaababbe81b35d80e1b91c4ad85\eventbus-3.0.0.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-media-compat\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.flyco.roundview\FlycoRoundView_Lib\1.1.4\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.tbruyelle.rxpermissions\rxpermissions\0.9.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.squareup.leakcanary\leakcanary-android\1.5\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.nineoldandroids\library\2.4.0\e9b63380f3a242dbdbf103a2355ad7e43bad17cb\library-2.4.0.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.squareup.leakcanary\leakcanary-analyzer\1.5\3277b0b0c2ace34a2edb5ddf9d1f67829561fb8f\leakcanary-analyzer-1.5.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\jp.wasabeef\blurry\2.1.0\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\io.reactivex\rxandroid\1.2.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\cardview-v7\24.0.0\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.zhy\okhttputils\2.6.2\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-compat\25.0.1\jars\classes.jar
==fastdex add jar C:\Android_SDK\extras\android\m2repository\com\android\support\support-annotations\25.0.1\support-annotations-25.0.1.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.timqi.collapsibletextview\library\1.1.2\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-core-utils\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.zhy\autolayout\1.4.5\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.jakewharton.hugo\hugo-annotations\1.2.1\b01150795c5cdca1eb7e501bf00f105ff0e31501\hugo-annotations-1.2.1.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\3.7.0\9e9eeaf9948ee4d6c3ab354e8dc14368f16994a4\glide-3.7.0.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.bm.photoview\library\1.4.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.luffykou\android-common-utils\1.1.3\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.3.1\19047bdb6a4fc00a44124f64ca98e88fc204e7e3\okhttp-3.3.1.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.github.markzhai\blockcanary-analyzer\1.5.0\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.2.1\4e4cfa4adc74521d5966799fa5ab70b733552f68\rxjava-1.2.1.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\1.8.0\5ea7af56cc7c567ed9856d99efb30740e9b17ff\okio-1.8.0.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\me.shaohui.advancedluban\library\1.3.2\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.jakewharton.hugo\hugo-runtime\1.2.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.soundcloud.android.crop\lib_crop\1.0.0\jars\classes.jar
==fastdex add jar C:\Users\MX\.gradle\caches\modules-2\files-2.1\com.squareup.leakcanary\leakcanary-watcher\1.5\288101b16513158c2923ad3fb6161d1452b65e73\leakcanary-watcher-1.5.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\com.android.support\support-fragment\25.0.1\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\LoveShowOnline\zeuslibrary\unspecified\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\LoveShowOnline\recyclerview_item_animator_library\unspecified\jars\classes.
jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\LoveShowOnline\SmallVideoLib\unspecified\jars\classes.jar
==fastdex add jar C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\exploded-aar\LoveShowOnline\mediapicker\unspecified\jars\classes.jar
==fastdex add dir ImmutableDirectoryInput{name=6e0d64dffc6591d40997f050306c86db4bdf2170, file=C:\Users\MX\AndroidStudioProjects\2.X\LoveShowOnline\app\build\intermediates\classes\debu
g, contentTypes=CLASSES, scopes=PROJECT, changedFiles={}}
:app:transformClassesWithDexForDebug FAILED          
              
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> ==fastdex normal transform merge jar fail:
outputJar: null

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: ==fastdex normal transform merge jar fail:
outputJar: null
        at com.dx168.fastdex.build.transform.FastdexTransform.transform(FastdexTransform.groovy:110)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more


BUILD FAILED
```

**Comment by typ0520** [comment]
@FancyOnePoint 找到问题了，有个bug，换0.0.3-beta6看下

**Comment by codeccc** [comment]
没遇到问题了,不过并没有感觉到有速度上的提升,感觉跟原来差不多

**Comment by typ0520** [comment]
@FancyOnePoint 第一次全量打包慢，以后就快了，不太可能没效果吧

**Comment by typ0520** [comment]
@FancyOnePoint 你试试最新版本0.0.4-beta，对一个dex的项目做了优化，性能提升很多
