### ISSUE TITLE
 warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

### ISSUE THREAD

**Issue by junchenChow** [typ0520/fastdex#17]
**[ant:javac] : warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
[ant:javac] /Users/zhoujunchen/as/xx/app/build/fastdex/DevelopDebug/custom-combind/com/xx/xx/xx/xx/CourseDetailActivity.java:229: 错误: -source 1.7 中不支持 lambda 表达式
[ant:javac]         wrapperControlsView.postDelayed(() -> wrapperControlsView.initiativeRefresh(), 500L);
[ant:javac]                                            ^
[ant:javac]   (请使用 -source 8 或更高版本以启用 lambda 表达式)
[ant:javac] /Users/zhoujunchen/as/android-donguo/app/build/fastdex/DevelopDebug/custom-combind/com/xx/xx/xx/xx/CourseDetailActivity.java:489: 错误: -source 1.7 中不支持方法引用
[ant:javac]                 .subscribe(conf -> ShareHelper.share(this, conf), Throwable::printStackTrace);
[ant:javac]                                                                              ^
[ant:javac]   (请使用 -source 8 或更高版本以启用方法引用)
[ant:javac] 2 个错误
:app:fastdexCustomCompileDevelopDebugJavaWithJavac FAILED**
有什么选项没开启么 不支持lambda？

**Comment by junchenChow** [comment]
可能还是不太适合我目前项目 编译出来的apk 有些地方用到了 activity的scheme action跳转 直接崩溃了。
**android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=weilaidao://ip.code/course?courseId=58772ceb8d459da56de19c9a }
                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1878)
                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:4283)
                                                                       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:4230)
                                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                       at android.app.Activity.startActivity(Activity.java:4567)
                                                                       at android.app.Activity.startActivity(Activity.java:4535)**

**Comment by typ0520** [comment]
@junchenChow  加一个配置关掉自定义的编译任务(这个任务目前不支持lambda，使用默认的是OK的)，刚才发了一个新版本，解决了一个bug随便换下吧  0.0.3-beta7

fastdex {
    useCustomCompile = false
}
