### ISSUE TITLE
com.dx168.fastdex.runtime.FastdexApplication cannot be cast to com.baidao.ytxmobile.application.YtxApplication

### ISSUE THREAD

**Issue by hexi** [typ0520/fastdex#2]
java.lang.ClassCastException: com.dx168.fastdex.runtime.FastdexApplication cannot be cast to com.baidao.ytxmobile.application.YtxApplication
                                                                         at com.baidao.ytxmobile.application.BaseFragment.onDestroy(BaseFragment.java:145)
                                                                         at com.baidao.ytxmobile.home.eventFragment.BaseEventFragment.onDestroy(BaseEventFragment.java:128)
                                                                         at android.support.v4.app.Fragment.performDestroy(Fragment.java:2202)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1196)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1349)
                                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:712)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                         at com.baidao.ytxmobile.support.adapter.IDFragmentStatePagerAdapter.finishUpdate(IDFragmentStatePagerAdapter.java:226)
                                                                         at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:476)
                                                                         at com.baidao.ytxmobile.home.HomeFragment.updateHomeMessageViewPager(HomeFragment.java:324)
                                                                         at com.baidao.ytxmobile.home.HomeFragment.access$200(HomeFragment.java:83)
                                                                         at com.baidao.ytxmobile.home.HomeFragment$5.call(HomeFragment.java:514)
                                                                         at com.baidao.ytxmobile.home.HomeFragment$5.call(HomeFragment.java:511)
                                                                         at com.baidao.ytxmobile.home.helper.MessageTabUtil$2.onNext(MessageTabUtil.java:99)
                                                                         at com.baidao.ytxmobile.home.helper.MessageTabUtil$2.onNext(MessageTabUtil.java:82)
                                                                         at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)`

**Comment by typ0520** [comment]
@hexi  出现这个问题的原因是把项目的Application代理掉了，在0.0.2-rc5这个版本中已解决，在运行期把代理Application换成了真正的Application
