### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > ==fastdex jar input size is 56, expected is 1

### ISSUE THREAD

**Issue by ysnows** [typ0520/fastdex#29]
大神，这个是什么原因导致的啊

**Comment by typ0520** [comment]
@ysnows 这个问题之前有个哥们报过一直无法重现，你能按这个[issue#11](https://github.com/typ0520/fastdex/issues/11) 里说的格式把完整的信息提交上来吗

**Comment by ysnows** [comment]
操作系统: mac  10.12.4 (16E195)
android gradle-build:2.3.1
gradle: 3.3-all


```
xianguajindeMBP:sample xianguangjin$ ./gradlew assembleDebug --stacktrace
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
====================fastdex====================
==fastdex android.buildTypes.product.minifyEnabled=true, just ignore
====================fastdex====================
==fastdex find jarmerging transform. transform class: class com.android.build.gradle.internal.transforms.JarMergingTransform . task name: transformClassesWithJarMergingForDebug
==fastdex find dex transform. transform class: class com.android.build.gradle.internal.transforms.DexTransform . task name: transformClassesWithDexForDebug
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:extractProguardFiles
:app:preProductBuild
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportMultidex101Library
:app:prepareComJakewhartonButterknife801Library
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid14Beta2Library
:app:prepareIoReactivexRxandroid120Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:processDebugManifest
:app:fastdexProcessDebugManifest
fastdex gen AndroidManifest.xml in AndroidManifest.xml
:app:fastdexProcessDebugResourceId
==fastdex apply resource mapping file /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/fastdex/Debug/r/R.txt is illegal, just ignore
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugResources
:app:generateDebugSources
:app:fastdexCustomCompileDebugJavaWithJavac
==fastdex clean dir: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/fastdex/Debug
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
注: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/generated/source/apt/debug/com/dx168/fastdex/sample/CustomView$$ViewBinder.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:transformClassesWithJarMergingForDebug
====fastdex inject dir: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug====
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/BuildConfig.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/CustomView$$ViewBinder$InnerUnbinder.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/CustomView$$ViewBinder.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/CustomView.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/MainActivity$1.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/MainActivity$2.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/MainActivity$T1.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/MainActivity$T2.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/MainActivity.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$attr.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$color.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$dimen.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$drawable.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$id.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$integer.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$layout.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$mipmap.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$string.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R$style.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/R.class
==fastdex inject: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/classes/debug/com/dx168/fastdex/sample/SampleApplication.class
==fastdex inject complete dir-size: 1 , use: 153ms
:app:fastdexCreateDebugMaindexlistFileTask
:app:transformClassesWithMultidexlistForDebug SKIPPED
:app:transformClassesWithDexForDebug
==fastdex normal transform start

Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html

Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.squareup.haha.guava.base.Joiner$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.squareup.haha.guava.collect.Iterables$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.squareup.haha.guava.collect.Iterables$3) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

==fastdex dex output directory: /Users/xianguangjin/Downloads/fastdex-master/sample/app/build/intermediates/transforms/dex/debug/folders/1000/1f/main
==fastdex first build cached_dex[classes.dex] cur-dex[classes.dex,classes2.dex]
==fastdex normal transform end
:app:mergeDebugJniLibFolders
:app:transformNativeLibsWithMergeJniLibsForDebug
:app:transformNativeLibsWithStripDebugSymbolForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 23.765 secs
Task spend time:
     77ms  :app:compileDebugAidl
    130ms  :app:generateDebugBuildConfig
    112ms  :app:processDebugManifest
     69ms  :app:fastdexProcessDebugManifest
    372ms  :app:mergeDebugResources
    181ms  :app:processDebugResources
     82ms  :app:fastdexCustomCompileDebugJavaWithJavac
   1788ms  :app:compileDebugJavaWithJavac
    643ms  :app:transformClassesWithJarMergingForDebug
   7807ms  :app:transformClassesWithDexForDebug
     70ms  :app:transformNativeLibsWithStripDebugSymbolForDebug
    414ms  :app:packageDebug


````

**Comment by ysnows** [comment]
这个是直接把你的demo拉下来运行的

**Comment by typ0520** [comment]
@ysnows  你之前报错是demo代码还是你自己的项目，最好提供一下打包出错时完整的日志

**Comment by ysnows** [comment]
之前是我自己的项目；我下载了demo也是这个错
```  

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> ==fastdex jar input size is 14, expected is 1 ```


然后用 命令行执行``` ./gradlew assembleDebug```是没有问题的；只有用按钮执行才会出现这个状况

**Comment by typ0520** [comment]
你把instant run关掉

**Comment by ysnows** [comment]
是关着的

**Comment by typ0520** [comment]
有个哥们报了同样的问题用命令行是好的，点击studio的run就有问题，估计你也是同样的问题

**Comment by ysnows** [comment]
`ANDROID_BUILD_TOOLS_VERSION=25.0.2` 的时候就会报这个错误，`ANDROID_BUILD_TOOLS_VERSION=25.0.0`的时候就不会报这个错误了

**Comment by HegemonyLei** [comment]
报了同样的问题，请问解决方案是什么？

**Comment by HegemonyLei** [comment]
org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:transformClassesWithDexForMmdAppTestDebug'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForMmdAppTestDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	... 44 more
Caused by: java.lang.RuntimeException: ==fastdex jar input size is 57, expected is 1
	at com.dx168.fastdex.build.transform.FastdexTransform.getCombinedJarFile(FastdexTransform.groovy:174)
	at com.dx168.fastdex.build.transform.FastdexTransform$getCombinedJarFile$0.callCurrent(Unknown Source)
	at com.dx168.fastdex.build.transform.FastdexTransform.generatePatchJar(FastdexTransform.groovy:190)
	at com.dx168.fastdex.build.transform.FastdexTransform$generatePatchJar$1.callCurrent(Unknown Source)
	at com.dx168.fastdex.build.transform.FastdexTransform.transform(FastdexTransform.groovy:72)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more

OS                        : windows 7
android_build_version     : 2.3.1
gradle_version            : 3.3
buildToolsVersion         : 25.0.2
compileSdkVersion         : android-25
default minSdkVersion     : 14
default targetSdkVersion  : 25
default multiDexEnabled   : true

fastdex build exception, welcome to submit issue to us: https://github.com/typ0520/fastdex/issues

**Comment by typ0520** [comment]
buildToolVersion改成25.0.0试试

**Comment by ysnows** [comment]
@typ0520 设置`multiDexEnabled=false`后可以正常运行

**Comment by typ0520** [comment]
@ysnows  已经在0.1.5版本解决
