### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by ysnows** [typ0520/fastdex#30]
操作系统: mac 10.12.4 (16E195)
android gradle-build:2.3.1
gradle: 3.3-all

又报这个错...

```* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> No signature of method: static com.dx168.fastdex.build.util.ClassInject.injectDirectoryInputFiles() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated, java.util.HashSet) values: [project ':app', [/Users/xianguangjin/Documents/AndroidStudio/Ant/app/build/intermediates/transforms/retrolambda/debug/folders/1/1/retrolambda]]
  Possible solutions: injectDirectoryInputFiles(com.dx168.fastdex.build.variant.FastdexVariant, java.util.Set)
```

全部日志：

```
xianguajindeMBP:Ant xianguangjin$ ./gradlew installDebug --stacktrace
Parallel execution is an incubating feature.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
====================fastdex====================
==fastdex android.buildTypes.release.minifyEnabled=true, just ignore
====================fastdex====================
==fastdex find dex transform. transform class: class com.android.build.gradle.internal.transforms.DexTransform . task name: transformClassesWithDexForDebug
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:extractProguardFiles
:app:preReleaseBuild
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:ysnows:preBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72531Library
:ysnows:preReleaseBuild UP-TO-DATE
:ysnows:checkReleaseManifest
:ysnows:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72531Library
:ysnows:preDebugBuild UP-TO-DATE
:ysnows:preDebugUnitTestBuild UP-TO-DATE
:ysnows:preReleaseUnitTestBuild UP-TO-DATE
:ysnows:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:ysnows:prepareComAndroidSupportAppcompatV72531Library
:app:prepareComAndroidSupportDesign2531Library
:ysnows:prepareComAndroidSupportConstraintConstraintLayout102Library
:ysnows:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportRecyclerviewV72531Library
:ysnows:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:ysnows:prepareComAndroidSupportSupportCompat2531Library
:ysnows:prepareComAndroidSupportSupportCoreUi2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:ysnows:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportFragment2531Library
:ysnows:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:ysnows:prepareComAndroidSupportSupportMediaCompat2531Library
:ysnows:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:ysnows:prepareComAndroidSupportSupportVectorDrawable2531Library
:ysnows:prepareComAndroidSupportTransition2531Library
:app:prepareComAndroidSupportTransition2531Library
:ysnows:prepareComDaimajiaSwipelayoutLibrary120Library
:app:prepareComCamnterEasyrecyclerviewEasyrecyclerview13Library
:app:prepareComDaimajiaSwipelayoutLibrary120Library
:ysnows:prepareComFacebookStethoStetho142Library
:app:prepareComElyeprojLibrariesLoaderviewlibrary122Library
:ysnows:prepareComFacebookStethoStethoOkhttp3142Library
:app:prepareComFacebookStethoStetho142Library
:ysnows:prepareComGithubChrisbanesPhotoView130Library
:app:prepareComFacebookStethoStethoOkhttp3142Library
:ysnows:prepareComGithubPromegTinypinyinAndroidAssetLexicons202Library
:app:prepareComGithubChrisbanesPhotoView130Library
:ysnows:prepareComGithubPromegTinypinyinLexiconsAndroidCncity202Library
:app:prepareComGithubPromegTinypinyinAndroidAssetLexicons202Library
:ysnows:prepareComGithubR21nomiAndroidrpinterpolator100Library
:app:prepareComGithubPromegTinypinyinLexiconsAndroidCncity202Library
:app:prepareComGithubR21nomiAndroidrpinterpolator100Library
:app:prepareComGithubZhaokaiqiangKlogLibrary001Library
:ysnows:prepareComGithubZhaokaiqiangKlogLibrary001Library
:ysnows:prepareComJaegerStatusbaruitlLibrary124Library
:app:prepareComJaegerStatusbaruitlLibrary124Library
:ysnows:prepareComTbruyelleRxpermissionsRxpermissions090Library
:app:prepareComJakewhartonButterknife801Library
:ysnows:prepareComYancyImageselectorImageselector133Library
:app:prepareComTbruyelleRxpermissionsRxpermissions090Library
:app:prepareComYancyImageselectorImageselector133Library
:app:prepareComYat3sLibraryBaseadapter011Library
:ysnows:prepareComYat3sLibraryBaseadapter011Library
:ysnows:prepareComZhyAutolayout145Library
:app:prepareComZhyAutolayout145Library
:ysnows:prepareComZhyOkhttputils262Library
:app:prepareComZhyOkhttputils262Library
:ysnows:prepareIoReactivexRxandroid121Library
:app:prepareIoReactivexRxandroid121Library
:app:prepareJpWasabeefRecyclerviewAnimators223Library
:ysnows:prepareJpWasabeefRecyclerviewAnimators223Library
:app:prepareMeYokeywordSwipebackfragment022Library
:ysnows:prepareMeYokeywordSwipebackfragment022Library
:ysnows:prepareReleaseDependencies
:ysnows:compileReleaseAidl
:app:generateDebugBuildConfig UP-TO-DATE
:ysnows:compileReleaseAidl UP-TO-DATE
:ysnows:compileReleaseNdk
:app:generateDebugResValues UP-TO-DATE
:app:fastdexCustomCompileDebugJavaWithJavac
:ysnows:compileReleaseNdk UP-TO-DATE
==fastdex clean dir: /Users/xianguangjin/Documents/AndroidStudio/Ant/app/build/fastdex/Debug
:ysnows:compileLint UP-TO-DATE
:ysnows:copyReleaseLint UP-TO-DATE
:ysnows:compileReleaseRenderscript UP-TO-DATE
:ysnows:generateReleaseBuildConfig UP-TO-DATE
:ysnows:generateReleaseResValues UP-TO-DATE
:ysnows:generateReleaseResources UP-TO-DATE
:ysnows:mergeReleaseResources
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileDebug
:app:compileDebugNdk UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:validateSigningDebug
:ysnows:mergeReleaseResources UP-TO-DATE
:ysnows:processReleaseManifest UP-TO-DATE
:ysnows:processReleaseResources UP-TO-DATE
:ysnows:generateReleaseSources UP-TO-DATE
:ysnows:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:ysnows:javaPreCompileRelease
:ysnows:compileReleaseJavaWithJavac UP-TO-DATE
:ysnows:extractReleaseAnnotations UP-TO-DATE
:ysnows:mergeReleaseShaders UP-TO-DATE
:ysnows:compileReleaseShaders UP-TO-DATE
:ysnows:generateReleaseAssets UP-TO-DATE
:ysnows:mergeReleaseAssets UP-TO-DATE
:ysnows:mergeReleaseProguardFiles UP-TO-DATE
:ysnows:packageReleaseRenderscript UP-TO-DATE
:ysnows:packageReleaseResources UP-TO-DATE
:ysnows:transformClassesWithRetrolambdaForRelease UP-TO-DATE
:ysnows:processReleaseJavaRes UP-TO-DATE
:ysnows:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:ysnows:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:ysnows:mergeReleaseJniLibFolders UP-TO-DATE
:ysnows:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:ysnows:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
:ysnows:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
:ysnows:bundleRelease UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:processDebugManifest
:app:fastdexProcessDebugManifest
fastdex gen AndroidManifest.xml in AndroidManifest.xml
:app:fastdexProcessDebugResourceId
==fastdex apply resource mapping file /Users/xianguangjin/Documents/AndroidStudio/Ant/app/build/fastdex/Debug/r/R.txt is illegal, just ignore
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:transformClassesWithRetrolambdaForDebug UP-TO-DATE
:app:transformClassesWithDexForDebug
==fastdex normal transform start
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> No signature of method: static com.dx168.fastdex.build.util.ClassInject.injectDirectoryInputFiles() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated, java.util.HashSet) values: [project ':app', [/Users/xianguangjin/Documents/AndroidStudio/Ant/app/build/intermediates/transforms/retrolambda/debug/folders/1/1/retrolambda]]
  Possible solutions: injectDirectoryInputFiles(com.dx168.fastdex.build.variant.FastdexVariant, java.util.Set)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: groovy.lang.MissingMethodException: No signature of method: static com.dx168.fastdex.build.util.ClassInject.injectDirectoryInputFiles() is applicable for argument types: (org.gradle.api.internal.project.DefaultProject_Decorated, java.util.HashSet) values: [project ':app', [/Users/xianguangjin/Documents/AndroidStudio/Ant/app/build/intermediates/transforms/retrolambda/debug/folders/1/1/retrolambda]]
Possible solutions: injectDirectoryInputFiles(com.dx168.fastdex.build.variant.FastdexVariant, java.util.Set)
        at com.dx168.fastdex.build.transform.FastdexTransform.transform(FastdexTransform.groovy:145)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more


BUILD FAILED

Total time: 3.841 secs
Task spend time:
    100ms  :ysnows:mergeReleaseResources
     52ms  :ysnows:processReleaseResources
     95ms  :ysnows:compileReleaseJavaWithJavac
     83ms  :ysnows:transformClassesWithRetrolambdaForRelease
    187ms  :app:processDebugManifest
    133ms  :app:mergeDebugResources
     62ms  :app:transformClassesWithRetrolambdaForDebug

```

**Comment by typ0520** [comment]
这是个兼容性问题，下个版本修复
