### ISSUE TITLE
日志停止在这地方 好长一段时间

### ISSUE THREAD

**Issue by tianshaokai** [typ0520/fastdex#35]
![image](https://cloud.githubusercontent.com/assets/6706496/25166060/085c937a-250c-11e7-9e4b-35c63050ebac.png)

Window7 

Gradle：gradle-3.2
Gradle plugin: com.android.tools.build:gradle:2.2.0

**Comment by tianshaokai** [comment]
运行起来后报错：

  Process: cn.wdcloud.communtiy.share.demo, PID: 12097
                                                   java.lang.RuntimeException: Unable to create application com.dx168.fastdex.runtime.FastdexApplication: java.lang.ClassCastException: com.dx168.fastdex.runtime.FastdexApplication cannot be cast to cn.wdcloud.aflibraries.components.AFApplication
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4729)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                    Caused by: java.lang.ClassCastException: com.dx168.fastdex.runtime.FastdexApplication cannot be cast to cn.wdcloud.aflibraries.components.AFApplication
                                                       at cn.wdcloud.aflibraries.components.AFApplication.onCreate(AFApplication.java:46)
                                                       at cn.wdcloud.aflibraries.components.AFMultiDexApplication.onCreate(AFMultiDexApplication.java:32)
                                                       at com.dx168.fastdex.runtime.FastdexApplication.onCreate(FastdexApplication.java:293)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4726)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
04-19 14:31:43.116 8249-9649/? I/WtEventController: Receive am_crash event for pid: 12097

**Comment by typ0520** [comment]
@tianshaokai 你暂时别在application的onCreate里做强制转换，下个版本解决

**Comment by tianshaokai** [comment]
我就按照你的步骤使用的，好像没有在application 里做特殊操作

**Comment by tianshaokai** [comment]
作者能不能多的讲解一下你开源库，说实话我把代码都下载下来了，完全不理解你的代码，对了是不是需要对Gradle 的所有api 要有个充分的理解呢，你那有没有Gradle的中文教程啊，看见官方文档真是头晕

**Comment by typ0520** [comment]
@tianshaokai  建议你先把gradle的生命周期回调和任务之间的依赖搞清楚，学习gradle你可以看这个项目https://github.com/davenkin/gradle-learning

**Comment by tianshaokai** [comment]
作者能否加下我q 呢，多交流学习一下Gradle 1575640686

**Comment by typ0520** [comment]
@tianshaokai  已经在0.1.5版本解决
