### ISSUE TITLE
java.lang.RuntimeException: ==fastdex jar input size is 117, expected is 1

### ISSUE THREAD

**Issue by Razhan** [typ0520/fastdex#36]
Caused by: java.lang.RuntimeException: ==fastdex jar input size is 117, expected is 1
	at com.dx168.fastdex.build.transform.FastdexTransform.getCombinedJarFile(FastdexTransform.groovy:173)
	at com.dx168.fastdex.build.transform.FastdexTransform$getCombinedJarFile.callCurrent(Unknown Source)
	at com.dx168.fastdex.build.transform.FastdexTransform.transform(FastdexTransform.groovy:131)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more

Fastdex build version     : 0.1.4
OS                        : windows 10
android_build_version     : 2.3.1
gradle_version            : 3.3
buildToolsVersion         : 25.0.1
compileSdkVersion         : android-25
default minSdkVersion     : 21
default targetSdkVersion  : 25
default multiDexEnabled   : true

fastdex build exception, welcome to submit issue to us: https://github.com/typ0520/fastdex/issues

**Comment by typ0520** [comment]
@Razhan  已经在0.1.5版本解决
