### ISSUE TITLE
首次编译没通过，请问一下这个是什么原因啊？说是找不到main这个参数

### ISSUE THREAD

**Issue by qiaoshouqing** [typ0520/fastdex#48]
Caused by: java.lang.NullPointerException: Cannot get property 'main' on null object
        at com.dx168.fastdex.build.util.ProjectSnapshoot.getProjectSrcDirSet(ProjectSnapshoot.gro
ovy:229)
        at com.dx168.fastdex.build.util.ProjectSnapshoot$getProjectSrcDirSet$0.callCurrent(Unknow
n Source)
        at com.dx168.fastdex.build.util.ProjectSnapshoot.prepareEnv(ProjectSnapshoot.groovy:88)
        at com.dx168.fastdex.build.util.ProjectSnapshoot$prepareEnv.call(Unknown Source)
        at com.dx168.fastdex.build.variant.FastdexVariant.prepareEnv(FastdexVariant.groovy:144)
        at com.dx168.fastdex.build.variant.FastdexVariant$prepareEnv.call(Unknown Source)
        at com.dx168.fastdex.build.task.FastdexPrepareTask.prepareContext(FastdexPrepareTask.groo
vy:20)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskActi
on.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskActi
on.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskActi
on.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(Execu
teActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Exec
uteActionsTaskExecuter.java:76)
        ... 70 more

不知道是不是自己项目配置的问题，求帮忙看下这个问题。

**Comment by typ0520** [comment]
你的sourceSet怎么配置的

**Comment by qiaoshouqing** [comment]
这样配置的
    sourceSets {
        main {
            aidl.srcDirs = ['src/main/java']
            jniLibs.srcDirs = ['libs']
        }
        oppo {
            manifest.srcFile 'src/cooperate/oppo/AndroidManifest.xml'
            java.srcDirs = ['src/cooperate/oppo/src']
            res.srcDirs = ['src/cooperate/oppo/res']
            assets.srcDirs = ['src/cooperate/oppo/assets']
            jniLibs.srcDirs = ['src/cooperate/oppo/libs']
        }

        vivo {
            manifest.srcFile 'src/cooperate/vivo/AndroidManifest.xml'
            java.srcDirs = ['src/cooperate/vivo/src']
            res.srcDirs = ['src/cooperate/vivo/res']
            assets.srcDirs = ['src/cooperate/vivo/assets']
            jniLibs.srcDirs = ['src/cooperate/vivo/libs']
        }

        instrumentTest.setRoot('tests')
        debug.setRoot('src/build-types/debug')
        release.setRoot('src/build-types/release')
    }

**Comment by typ0520** [comment]
在build.gradle中配置上这段
```
project.afterEvaluate {
    android.applicationVariants.all { variant ->
        println("=============${variant.name}")
        if ("listeningDebug".equals(variant.name)) {
            project.tasks.findByName("processOppoDebugManifest").doFirst {
                println("======================================")
                println(project.android.sourceSets)
                println("========================project.android.sourceSets.main")
                println(project.android.sourceSets.main)
                println("========================project.android.sourceSets.main.java")
                println(project.android.sourceSets.main.java)
                println("========================project.android.sourceSets.main.java.srcDirs")
                println(project.android.sourceSets.main.java.srcDirs)
                println("======================================")
            }
        }
    }
}
```

在命令行中执行
```
./gradlew processOppoDebugManifest
```

执行完以后把日志贴上来啊

**Comment by qiaoshouqing** [comment]
你是要看目录结构吗？我直接给你截下图吧。那代码运行的时候报不能invoke all()这个函数。
 http://wx1.sinaimg.cn/mw690/6aa88161gy1fhn2p49r2dj207k0ar0st.jpg

**Comment by typ0520** [comment]
我的qq 752554930，qq说吧
