### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by zyl409214686** [typ0520/fastdex#49]
操作系统: mac
android gradle-build: 2.2.2
gradle: 2.1.4.1

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
beijing
writeCurrentFlavor=='beijing'.
Incremental java compilation is an incubating feature.
-hasApp = true
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = huairou
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = huairou
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = luzhou
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = luzhou
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = dongchengedu
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = dongchengedu
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = beijing
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = beijing
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = miyu
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = miyu
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = toon
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = toon
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = mencheng
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = mencheng
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = debug
-DexKnifePlugin flavorName = instantdev
-just activity size = 2
-DexKnifePlugin Enable = false
-DexKnifePlugin Enable = true
-DexKnifePlugin checkProductFlavor = true
-DexKnifePlugin checkBuildType = true
-DexKnifePlugin buildType.name = release
-DexKnifePlugin flavorName = instantdev
-just activity size = 2
-DexKnifePlugin Enable = false
:SystoonIm:preBuild UP-TO-DATE
:SystoonIm:preReleaseBuild UP-TO-DATE
:SystoonIm:checkReleaseManifest
:SystoonIm:preDebugAndroidTestBuild UP-TO-DATE
:SystoonIm:preDebugBuild UP-TO-DATE
:SystoonIm:preDebugUnitTestBuild UP-TO-DATE
:SystoonIm:preReleaseUnitTestBuild UP-TO-DATE
:SystoonIm:prepareComAndroidSupportAnimatedVectorDrawable2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportAppcompatV72500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportCompat2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportCoreUi2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportCoreUtils2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportFragment2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportMediaCompat2500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportV42500Library UP-TO-DATE
:SystoonIm:prepareComAndroidSupportSupportVectorDrawable2500Library UP-TO-DATE
:SystoonIm:prepareComMeizuFlymeInternetPushInternalPublish33170505Library UP-TO-DATE
:SystoonIm:prepareReleaseDependencies
:SystoonIm:compileReleaseAidl UP-TO-DATE
:SystoonIm:compileReleaseNdk UP-TO-DATE
:SystoonIm:compileLint UP-TO-DATE
:SystoonIm:copyReleaseLint UP-TO-DATE
:SystoonIm:compileReleaseRenderscript UP-TO-DATE
:SystoonIm:generateReleaseBuildConfig UP-TO-DATE
:SystoonIm:generateReleaseResValues UP-TO-DATE
:SystoonIm:generateReleaseResources UP-TO-DATE
:SystoonIm:mergeReleaseResources UP-TO-DATE
:SystoonIm:processReleaseManifest UP-TO-DATE
:SystoonIm:processReleaseResources UP-TO-DATE
:SystoonIm:generateReleaseSources UP-TO-DATE
:SystoonIm:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:SystoonIm:compileReleaseJavaWithJavac UP-TO-DATE
:SystoonIm:extractReleaseAnnotations UP-TO-DATE
:SystoonIm:mergeReleaseShaders UP-TO-DATE
:SystoonIm:compileReleaseShaders UP-TO-DATE
:SystoonIm:generateReleaseAssets UP-TO-DATE
:SystoonIm:mergeReleaseAssets UP-TO-DATE
:SystoonIm:mergeReleaseProguardFiles UP-TO-DATE
:SystoonIm:packageReleaseRenderscript UP-TO-DATE
:SystoonIm:packageReleaseResources UP-TO-DATE
:SystoonIm:processReleaseJavaRes UP-TO-DATE
:SystoonIm:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:SystoonIm:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:SystoonIm:mergeReleaseJniLibFolders UP-TO-DATE
:SystoonIm:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:SystoonIm:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:SystoonIm:bundleRelease UP-TO-DATE
:SystoonMedia:preBuild UP-TO-DATE
:SystoonMedia:preReleaseBuild UP-TO-DATE
:SystoonMedia:checkReleaseManifest
:SystoonMedia:prepareReleaseDependencies
:SystoonMedia:compileReleaseAidl UP-TO-DATE
:SystoonMedia:compileReleaseNdk UP-TO-DATE
:SystoonMedia:compileLint UP-TO-DATE
:SystoonMedia:copyReleaseLint UP-TO-DATE
:SystoonMedia:mergeReleaseShaders UP-TO-DATE
:SystoonMedia:compileReleaseShaders UP-TO-DATE
:SystoonMedia:generateReleaseAssets UP-TO-DATE
:SystoonMedia:mergeReleaseAssets UP-TO-DATE
:SystoonMedia:mergeReleaseProguardFiles UP-TO-DATE
:SystoonMedia:packageReleaseRenderscript UP-TO-DATE
:SystoonMedia:compileReleaseRenderscript UP-TO-DATE
:SystoonMedia:generateReleaseResValues UP-TO-DATE
:SystoonMedia:generateReleaseResources UP-TO-DATE
:SystoonMedia:packageReleaseResources UP-TO-DATE
:SystoonMedia:processReleaseManifest UP-TO-DATE
:SystoonMedia:generateReleaseBuildConfig UP-TO-DATE
:SystoonMedia:processReleaseResources UP-TO-DATE
:SystoonMedia:generateReleaseSources UP-TO-DATE
:SystoonMedia:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:SystoonMedia:compileReleaseJavaWithJavac UP-TO-DATE
:SystoonMedia:processReleaseJavaRes UP-TO-DATE
:SystoonMedia:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:SystoonMedia:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:SystoonMedia:mergeReleaseJniLibFolders UP-TO-DATE
:SystoonMedia:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:SystoonMedia:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:SystoonMedia:bundleRelease UP-TO-DATE
:Toon:preBuild UP-TO-DATE
:Toon:preBeijingDebugBuild UP-TO-DATE
:Toon:checkBeijingDebugManifest
:Toon:greendaoPrepare UP-TO-DATE
:Toon:greendao UP-TO-DATE
:Toon:preBeijingReleaseBuild UP-TO-DATE
:Toon:preDongchengeduDebugBuild UP-TO-DATE
:Toon:preDongchengeduReleaseBuild UP-TO-DATE
:Toon:preHuairouDebugBuild UP-TO-DATE
:Toon:preHuairouReleaseBuild UP-TO-DATE
:Toon:preInstantdevDebugBuild UP-TO-DATE
:Toon:preInstantdevReleaseBuild UP-TO-DATE
:Toon:preLuzhouDebugBuild UP-TO-DATE
:Toon:preLuzhouReleaseBuild UP-TO-DATE
:Toon:preMenchengDebugBuild UP-TO-DATE
:Toon:preMenchengReleaseBuild UP-TO-DATE
:Toon:preMiyuDebugBuild UP-TO-DATE
:Toon:preMiyuReleaseBuild UP-TO-DATE
:Toon:preToonDebugBuild UP-TO-DATE
:Toon:preToonReleaseBuild UP-TO-DATE
:systoonCore:SystoonCore:preBuild UP-TO-DATE
:systoonCore:SystoonCore:preReleaseBuild UP-TO-DATE
:systoonCore:SystoonCore:checkReleaseManifest
:systoonCore:SystoonCore:preDebugAndroidTestBuild UP-TO-DATE
:systoonCore:SystoonCore:preDebugBuild UP-TO-DATE
:systoonCore:SystoonCore:preDebugUnitTestBuild UP-TO-DATE
:systoonCore:SystoonCore:preReleaseUnitTestBuild UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportAnimatedVectorDrawable2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportAppcompatV72500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportCompat2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportCoreUi2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportCoreUtils2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportFragment2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportMediaCompat2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportV42500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComAndroidSupportSupportVectorDrawable2500Library UP-TO-DATE
:systoonCore:SystoonCore:prepareComKoushikduttaAsyncAndroidasync219Library UP-TO-DATE
:systoonCore:SystoonCore:prepareIoReactivexRxandroid121Library UP-TO-DATE
:systoonCore:SystoonCore:prepareNetZeteticAndroidDatabaseSqlcipher354Library UP-TO-DATE
:systoonCore:SystoonCore:prepareReleaseDependencies
:systoonCore:SystoonCore:compileReleaseAidl UP-TO-DATE
:systoonCore:SystoonCore:compileReleaseNdk UP-TO-DATE
:systoonCore:SystoonCore:compileLint UP-TO-DATE
:systoonCore:SystoonCore:copyReleaseLint UP-TO-DATE
:systoonCore:SystoonCore:buildNative
Android NDK: WARNING: APP_PLATFORM android-23 is larger than android:minSdkVersion 14 in /Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/systoonCore/SystoonCore/AndroidManifest.xml    
make: Entering directory `/Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/systoonCore/SystoonCore/jni'
[armeabi] Install        : libcom_systoon_gif.so => libs/armeabi/libcom_systoon_gif.so
[armeabi] Install        : libcom_systoon_gif_surface.so => libs/armeabi/libcom_systoon_gif_surface.so
[x86] Install        : libcom_systoon_gif.so => libs/x86/libcom_systoon_gif.so
[x86] Install        : libcom_systoon_gif_surface.so => libs/x86/libcom_systoon_gif_surface.so
make: Leaving directory `/Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/systoonCore/SystoonCore/jni'
:systoonCore:SystoonCore:compileReleaseRenderscript UP-TO-DATE
:systoonCore:SystoonCore:generateReleaseBuildConfig UP-TO-DATE
:systoonCore:SystoonCore:generateReleaseResValues UP-TO-DATE
:systoonCore:SystoonCore:generateReleaseResources UP-TO-DATE
:systoonCore:SystoonCore:mergeReleaseResources UP-TO-DATE
:systoonCore:SystoonCore:processReleaseManifest UP-TO-DATE
:systoonCore:SystoonCore:processReleaseResources UP-TO-DATE
:systoonCore:SystoonCore:generateReleaseSources UP-TO-DATE
:systoonCore:SystoonCore:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:systoonCore:SystoonCore:compileReleaseJavaWithJavac UP-TO-DATE
:systoonCore:SystoonCore:extractReleaseAnnotations UP-TO-DATE
:systoonCore:SystoonCore:mergeReleaseShaders UP-TO-DATE
:systoonCore:SystoonCore:compileReleaseShaders UP-TO-DATE
:systoonCore:SystoonCore:generateReleaseAssets UP-TO-DATE
:systoonCore:SystoonCore:mergeReleaseAssets UP-TO-DATE
:systoonCore:SystoonCore:mergeReleaseProguardFiles UP-TO-DATE
:systoonCore:SystoonCore:packageReleaseRenderscript UP-TO-DATE
:systoonCore:SystoonCore:packageReleaseResources UP-TO-DATE
:systoonCore:SystoonCore:processReleaseJavaRes UP-TO-DATE
:systoonCore:SystoonCore:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:systoonCore:SystoonCore:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:systoonCore:SystoonCore:mergeReleaseJniLibFolders UP-TO-DATE
:systoonCore:SystoonCore:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:systoonCore:SystoonCore:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:systoonCore:SystoonCore:bundleRelease UP-TO-DATE
:Toon:prepareBeaconlibLibrary UP-TO-DATE
:Toon:prepareComAlipayEulerAndfix050Library UP-TO-DATE
:Toon:prepareComAndroidSupportAnimatedVectorDrawable2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportAppcompatV72530Library UP-TO-DATE
:Toon:prepareComAndroidSupportDesign2530Library UP-TO-DATE
:Toon:preBeijingDebugAndroidTestBuild UP-TO-DATE
:Toon:preDongchengeduDebugAndroidTestBuild UP-TO-DATE
:Toon:preHuairouDebugAndroidTestBuild UP-TO-DATE
:Toon:preLuzhouDebugAndroidTestBuild UP-TO-DATE
:Toon:preMenchengDebugAndroidTestBuild UP-TO-DATE
:Toon:preMiyuDebugAndroidTestBuild UP-TO-DATE
:Toon:preToonDebugAndroidTestBuild UP-TO-DATE
:Toon:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:Toon:prepareComAndroidSupportRecyclerviewV72530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportCompat2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportCoreUi2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportCoreUtils2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportFragment2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportMediaCompat2530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportV42530Library UP-TO-DATE
:Toon:prepareComAndroidSupportSupportVectorDrawable2530Library UP-TO-DATE
:Toon:preInstantdevDebugAndroidTestBuild UP-TO-DATE
:Toon:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library UP-TO-DATE
:Toon:prepareComAndroidSupportTransition2530Library UP-TO-DATE
:Toon:prepareComGithubModuthBlockcanary102Library UP-TO-DATE
:Toon:prepareComKoushikduttaAsyncAndroidasync219Library UP-TO-DATE
:Toon:prepareComMeizuFlymeInternetPushInternalPublish33170505Library UP-TO-DATE
:Toon:prepareComSensorsdataAnalyticsAndroidSensorsAnalyticsSDK171Library UP-TO-DATE
:Toon:prepareComSquareupLeakcanaryLeakcanaryAndroid131Library UP-TO-DATE
:Toon:prepareComTencentBuglyCrashreport231Library UP-TO-DATE
:Toon:prepareIoReactivexRxandroid121Library UP-TO-DATE
:Toon:prepareNetZeteticAndroidDatabaseSqlcipher354Library UP-TO-DATE
:Toon:prepareOrgAltbeaconAndroidBeaconLibrary2111G16fac9dLibrary UP-TO-DATE
:Toon:preparePayegisauthenticationsdkArmLibrary UP-TO-DATE
:Toon:prepareToonandroidSystoonCoreSystoonCoreUnspecifiedLibrary UP-TO-DATE
:Toon:prepareToonandroidSystoonImUnspecifiedLibrary UP-TO-DATE
:Toon:prepareToonandroidSystoonMediaUnspecifiedLibrary UP-TO-DATE
:Toon:prepareBeijingDebugDependencies
:Toon:compileBeijingDebugRenderscript UP-TO-DATE
:Toon:generateBeijingDebugResValues UP-TO-DATE
:Toon:generateBeijingDebugResources UP-TO-DATE
:Toon:mergeBeijingDebugResources UP-TO-DATE
:Toon:processBeijingDebugManifest
/Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/Toon/AndroidManifest.xml:47:5-71 Warning:
        Element uses-permission#android.permission.RECORD_AUDIO at AndroidManifest.xml:47:5-71 duplicated with element declared at AndroidManifest.xml:35:5-71
[toonandroid:SystoonIm:unspecified] /Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/Toon/build/intermediates/exploded-aar/toonandroid/SystoonIm/unspecified/AndroidManifest.xml:20:5-81 Warning:
        Element uses-permission#android.permission.RECEIVE_BOOT_COMPLETED at [toonandroid:SystoonIm:unspecified] AndroidManifest.xml:20:5-81 duplicated with element declared at [toonandroid:SystoonIm:unspecified] AndroidManifest.xml:11:5-81
:Toon:fastdexProcessBeijingDebugManifest
:Toon:fastdexProcessBeijingDebugResourceId
==fastdex apply resource mapping file /Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/Toon/build/fastdex/BeijingDebug/r/r.txt is illegal, just ignore
:Toon:processBeijingDebugResources UP-TO-DATE
:Toon:fastdexPrepareForBeijingDebug
==fastdex clean dir: /Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid/Toon/build/fastdex/BeijingDebug
:Toon:compileBeijingDebugAidl UP-TO-DATE
:Toon:generateBeijingDebugBuildConfig UP-TO-DATE
:Toon:generateBeijingDebugSources UP-TO-DATE
:Toon:incrementalBeijingDebugJavaCompilationSafeguard UP-TO-DATE
:Toon:compileBeijingDebugJavaWithJavac UP-TO-DATE
:Toon:compileBeijingDebugNdk UP-TO-DATE
:Toon:compileBeijingDebugSources UP-TO-DATE
:Toon:mergeBeijingDebugShaders UP-TO-DATE
:Toon:compileBeijingDebugShaders UP-TO-DATE
:Toon:generateBeijingDebugAssets UP-TO-DATE
:Toon:mergeBeijingDebugAssets UP-TO-DATE
:Toon:networkBenchNewLensInstrumentTask
[NBSAgent.debug] NetworkBench begin
[NBSAgent.info] project root:/Users/zouyulong/develop/company/syswin/beijingtoon/toonandroid
:Toon:transformClassesWithJarMergingForBeijingDebug UP-TO-DATE
:Toon:fastdexCreateBeijingDebugMaindexlistFileTask
:Toon:transformClassesWithMultidexlistForBeijingDebug SKIPPED
:Toon:transformClassesWithDexForBeijingDebug
DexKnife Processing ...
:Toon:transformClassesWithDexForBeijingDebug FAILED
:Toon:networkBenchNewLensDeinstrumentTask
[NBSAgent.debug] NetworkBench begin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Toon:transformClassesWithDexForBeijingDebug'.
> Cannot cast object 'fastdex.build.transform.FastdexTransform@1a67f86a' with class 'fastdex.build.transform.FastdexTransform' to class 'com.android.build.gradle.internal.transforms.DexTransform'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Toon:transformClassesWithDexForBeijingDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'fastdex.build.transform.FastdexTransform@1a67f86a' with class 'fastdex.build.transform.FastdexTransform' to class 'com.android.build.gradle.internal.transforms.DexTransform'
        at com.ceabie.dexknife.SplitToolsFor150$_processSplitDex_closure3.doCall(SplitToolsFor150.groovy:79)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more

BUILD FAILED

**Comment by typ0520** [comment]
你是不是加了一些别的插件进去了，这个错误应该是某个插件对Transform做了强制转换
