### ISSUE TITLE
【asset目录找不到文件】java.lang.RuntimeException: Font asset not found 

### ISSUE THREAD

**Issue by ycdm** [typ0520/fastdex#56]
09-20 23:25:58.605 19658-19658/cn.demo.package.demo E/AndroidRuntime: FATAL EXCEPTION: main
Process: cn.demo.package.demo, PID: 19658
**java.lang.RuntimeException: Unable to create application fastdex.runtime.FastdexApplication: java.lang.RuntimeException: Font asset not found fonts/DINCondensedBold.ttf**
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
**Caused by: java.lang.RuntimeException: Font asset not found fonts/DINCondensedBold.ttf**
at android.graphics.Typeface.createFromAsset(Typeface.java:206)
at cn.demo.package.utils.AppFont.init(AppFont.java:56)
at cn.demo.package.core.AppGlobal.initAppGlobal(AppGlobal.java:149)
at com.zztzt.android.simple.app.MainApplication.onCreate(MainApplication.java:137)
at fastdex.runtime.FastdexApplication.onCreate(FastdexApplication.java:138)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
at android.app.ActivityThread.-wrap2(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6186) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ycdm** [comment]
Typeface typeface = Typeface.createFromAsset(context.getAssets(), "fonts/DINCondensedBold.ttf");

**Comment by ycdm** [comment]
但是 run fastdex 运行两次之后就能正常启动

**Comment by ycdm** [comment]
还有一个报错：
                                                                      java.lang.RuntimeException: 修改了抽象类导致的错误,Fastdex已经为你自动恢复状态，重新执行一次fastdexDEVDebug任务就可以解决这个问题了



这个是什么意思？重新运行一下就好了吗？

**Comment by typ0520** [comment]
在运行一次会触发一次安装就好了，里面用到了qq空间的那个热修复的技术，这个在art下修改抽象类会报这个问题的，5.0以前的设备不会报这个问题

**Comment by typ0520** [comment]
你之前说的找不到assets内容的问题，如果在发现可以看下/data/data/包名/fastdex/patch/res/resources.apk  里面有没有对应的资源

**Comment by typ0520** [comment]
@ycdm 问题解决了，换成0.8.4
