### ISSUE TITLE
 android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by junchenChow** [typ0520/fastdex#61]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=weilaidao://ip.code/masters }
                                                                     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
                                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                                                                     at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                                     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                     at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                     at android.app.Activity.startActivity(Activity.java:4200)
                                                                     at android.app.Activity.startActivity(Activity.java:4168)
只要是通过scheme模式跳转的activity都找不到

**Comment by junchenChow** [comment]
有人么？

**Comment by typ0520** [comment]
这些activity有在清单文件配置吗

**Comment by junchenChow** [comment]
都有的 我项目页面之间的跳转是通过清单文件的scheme 用path来匹配 

类似路由的模式 这个可以看下

**<activity
          android:name="xxx.xxx.ThematicRecommendActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="@string/app_uri_host"
                    android:path="/recTag"
                    android:scheme="@string/app_schema" />
            </intent-filter>
</activity－>**


@typ0520

**Comment by typ0520** [comment]
如果有时间帮弄一个可以重现这个问题的demo项目，现在想不到那些地方会导致这问题

**Comment by fanei** [comment]
@junchenChow  解决这个问题了吗
